// KT Document Generator Service
export const generateKTDocument = (repoData, selectedFile = null) => {
  const today = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  if (selectedFile) {
    // Single file KT document
    return generateFileKT(selectedFile, repoData, today);
  } else {
    // Complete repository KT document
    return generateRepoKT(repoData, today);
  }
};

// Generate KT for single file
const generateFileKT = (file, repoData, today) => {
  const fileContent = getFileContentForKT(file.name);
  const dependencies = repoData.dependencies.filter(
    d => d.from === file.name || d.to === file.name
  );
  
  let doc = `# 📄 Knowledge Transfer Document: ${file.name}\n\n`;
  
  // Header
  doc += `**Generated:** ${today}\n`;
  doc += `**Repository:** ${repoData.name}\n`;
  doc += `**File Path:** ${file.path}\n\n`;
  
  // File Overview
  doc += `## 📋 File Overview\n\n`;
  doc += `| Metric | Value |\n`;
  doc += `|--------|-------|\n`;
  doc += `| Lines of Code | ${file.lines || 'N/A'} |\n`;
  doc += `| Complexity Score | ${file.complexity || 'N/A'}/10 |\n`;
  doc += `| Issues Found | ${file.issues || 0} |\n`;
  doc += `| Dependencies | ${dependencies.length} |\n\n`;
  
  // File Purpose
  doc += `## 🎯 Purpose\n\n`;
  doc += `${getFilePurpose(file.name)}\n\n`;
  
  // Code Structure
  doc += `## 🏗️ Code Structure\n\n`;
  doc += `${getFileStructure(file.name, fileContent)}\n\n`;
  
  // Functions
  const functions = extractFunctionsFromContent(fileContent);
  if (functions.length > 0) {
    doc += `## ⚙️ Functions\n\n`;
    functions.forEach((func, index) => {
      doc += `### ${index + 1}. \`${func.name}\`\n`;
      doc += `- **Line:** ${func.line}\n`;
      doc += `- **Purpose:** ${func.purpose}\n`;
      doc += `- **Parameters:** ${func.params}\n\n`;
    });
  }
  
  // Dependencies
  if (dependencies.length > 0) {
    doc += `## 🔗 Dependencies\n\n`;
    doc += `**Imported By:**\n`;
    dependencies.filter(d => d.to === file.name).forEach(d => {
      doc += `- \`${d.from}\`\n`;
    });
    doc += `\n**Imports:**\n`;
    dependencies.filter(d => d.from === file.name).forEach(d => {
      doc += `- \`${d.to}\`\n`;
    });
    doc += '\n';
  }
  
  // Recent Changes
  doc += `## 📝 Recent Changes\n\n`;
  doc += `| Date | Author | Description |\n`;
  doc += `|------|--------|-------------|\n`;
  doc += `| ${today} | System | Initial KT document generated |\n`;
  
  // Suggestions
  doc += `\n## 💡 Recommendations\n\n`;
  if (file.complexity > 7) {
    doc += `- ⚠️ **High Complexity:** Consider breaking down this file into smaller modules\n`;
  }
  if (file.issues > 0) {
    doc += `- 🔍 **Issues Found:** ${file.issues} issues need attention\n`;
  }
  doc += `- 📚 **Documentation:** Add more comments for complex logic\n`;
  doc += `- ✅ **Testing:** Ensure unit tests cover main functionality\n\n`;
  
  // Code Preview
  doc += `## 🔍 Code Preview\n\n`;
  doc += '```javascript\n';
  doc += fileContent.substring(0, 500);
  if (fileContent.length > 500) {
    doc += '\n// ... (truncated)';
  }
  doc += '\n```\n\n';
  
  // Footer
  doc += `---\n`;
  doc += `*Generated by Codebase Archaeologist KT Generator*\n`;
  doc += `*For questions, use the AI chat feature*\n`;
  
  return doc;
};

// Generate KT for entire repository
const generateRepoKT = (repoData, today) => {
  let doc = `# 📚 Knowledge Transfer Document: ${repoData.name}\n\n`;
  
  // Header
  doc += `**Generated:** ${today}\n`;
  doc += `**Repository URL:** ${repoData.url}\n\n`;
  
  // Repository Overview
  doc += `## 📊 Repository Overview\n\n`;
  doc += `| Metric | Value |\n`;
  doc += `|--------|-------|\n`;
  doc += `| Total Files | ${repoData.files.length} |\n`;
  doc += `| Total Lines | ${repoData.stats.totalLines} |\n`;
  doc += `| Dependencies | ${repoData.dependencies.length} |\n`;
  doc += `| Complexity | ${repoData.stats.complexity}% |\n`;
  doc += `| Tech Debt | ${repoData.stats.techDebt}% |\n\n`;
  
  // Languages
  doc += `## 🛠️ Languages Used\n\n`;
  Object.entries(repoData.stats.languages).forEach(([lang, percentage]) => {
    doc += `- **${lang}:** ${percentage}%\n`;
  });
  doc += '\n';
  
  // Project Structure
  doc += `## 📁 Project Structure\n\n`;
  
  // Group files by folder
  const folders = {};
  repoData.files.forEach(file => {
    const folder = file.path.split('/')[0] || 'root';
    if (!folders[folder]) folders[folder] = [];
    folders[folder].push(file);
  });
  
  Object.entries(folders).forEach(([folder, files]) => {
    doc += `### 📂 ${folder}/\n\n`;
    files.forEach(file => {
      const complexityIcon = file.complexity > 7 ? '⚠️' : file.complexity > 4 ? '📊' : '✅';
      doc += `- ${complexityIcon} \`${file.name}\` (${file.lines} lines, complexity: ${file.complexity}/10)\n`;
    });
    doc += '\n';
  });
  
  // Key Components
  doc += `## 🔑 Key Components\n\n`;
  
  const mainFiles = repoData.files.filter(f => 
    f.name.includes('App') || 
    f.name.includes('main') || 
    f.name.includes('index')
  );
  
  mainFiles.forEach(file => {
    doc += `### ${file.name}\n`;
    doc += `- **Path:** ${file.path}\n`;
    doc += `- **Purpose:** ${getFilePurpose(file.name)}\n`;
    doc += `- **Complexity:** ${file.complexity}/10\n\n`;
  });
  
  // Dependencies Map
  doc += `## 🔗 Dependency Map\n\n`;
  doc += `Total dependencies: ${repoData.dependencies.length}\n\n`;
  doc += `**Top Dependencies:**\n`;
  
  // Count dependency frequency
  const depCount = {};
  repoData.dependencies.forEach(d => {
    depCount[d.from] = (depCount[d.from] || 0) + 1;
  });
  
  const topDeps = Object.entries(depCount)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);
  
  topDeps.forEach(([file, count]) => {
    doc += `- \`${file}\` is used by ${count} other files\n`;
  });
  doc += '\n';
  
  // Complexity Analysis
  doc += `## 📈 Complexity Analysis\n\n`;
  
  const highComplexity = repoData.files.filter(f => f.complexity > 7);
  const mediumComplexity = repoData.files.filter(f => f.complexity > 4 && f.complexity <= 7);
  const lowComplexity = repoData.files.filter(f => f.complexity <= 4);
  
  doc += `- 🔴 **High Complexity:** ${highComplexity.length} files\n`;
  doc += `- 🟡 **Medium Complexity:** ${mediumComplexity.length} files\n`;
  doc += `- 🟢 **Low Complexity:** ${lowComplexity.length} files\n\n`;
  
  if (highComplexity.length > 0) {
    doc += `**Files needing attention:**\n`;
    highComplexity.forEach(f => {
      doc += `- ⚠️ \`${f.name}\` (${f.complexity}/10)\n`;
    });
    doc += '\n';
  }
  
  // Technical Debt
  doc += `## 💰 Technical Debt\n\n`;
  doc += `Overall tech debt: **${repoData.stats.techDebt}%**\n\n`;
  
  const filesWithIssues = repoData.files.filter(f => f.issues > 0);
  if (filesWithIssues.length > 0) {
    doc += `**Files with issues:**\n`;
    filesWithIssues.forEach(f => {
      doc += `- \`${f.name}\`: ${f.issues} issue(s)\n`;
    });
    doc += '\n';
  }
  
  // Recommendations
  doc += `## 💡 Recommendations for New Developers\n\n`;
  doc += `1. **Start with main files:** Begin by understanding \`App.jsx\` and \`index.js\`\n`;
  doc += `2. **Review complex files first:** Focus on high-complexity files listed above\n`;
  doc += `3. **Understand dependencies:** Check the dependency map to see how files connect\n`;
  doc += `4. **Use the AI chat:** Ask questions about specific files using the chat feature\n`;
  doc += `5. **Run tests:** Ensure you can run the application locally\n\n`;
  
  // Getting Started
  doc += `## 🚀 Getting Started\n\n`;
  doc += `\`\`\`bash\n`;
  doc += `# Clone the repository\n`;
  doc += `git clone ${repoData.url}\n\n`;
  doc += `# Install dependencies\n`;
  doc += `npm install\n\n`;
  doc += `# Run the project\n`;
  doc += `npm start\n`;
  doc += `\`\`\`\n\n`;
  
  // Footer
  doc += `---\n`;
  doc += `*This KT document was automatically generated by Codebase Archaeologist*\n`;
  doc += `*Last updated: ${today}*\n`;
  
  return doc;
};

// Helper: Get file purpose
const getFilePurpose = (fileName) => {
  if (fileName.includes('App')) {
    return 'Main application component that serves as the entry point for the UI. Handles routing and global state.';
  }
  if (fileName.includes('Button')) {
    return 'Reusable button component with multiple variants (primary, secondary, etc.). Used throughout the application.';
  }
  if (fileName.includes('api')) {
    return 'API service layer that handles all HTTP requests to backend services. Includes error handling and request formatting.';
  }
  if (fileName.includes('util') || fileName.includes('helper')) {
    return 'Utility functions and helpers used across the application. Contains reusable logic.';
  }
  if (fileName.includes('style') || fileName.includes('css')) {
    return 'Stylesheet containing CSS rules and design tokens for the application.';
  }
  return 'Core application file containing business logic and functionality.';
};

// Helper: Get file structure
const getFileStructure = (fileName, content) => {
  if (fileName.includes('.jsx')) {
    return 'React component file with JSX syntax. Contains component definition, props, and render logic.';
  }
  if (fileName.includes('.js')) {
    return 'JavaScript module with functions and logic. Exports specific functionality.';
  }
  if (fileName.includes('.css')) {
    return 'Stylesheet with CSS rules, classes, and media queries.';
  }
  return 'Standard code file with functions and logic.';
};

// Helper: Extract functions from content
const extractFunctionsFromContent = (content) => {
  const functions = [];
  const lines = content.split('\n');
  
  const patterns = [
    { regex: /function\s+(\w+)\s*\(([^)]*)\)/, type: 'function' },
    { regex: /const\s+(\w+)\s*=\s*\(([^)]*)\)\s*=>/, type: 'arrow' },
    { regex: /const\s+(\w+)\s*=\s*async\s*\(([^)]*)\)/, type: 'async' }
  ];
  
  lines.forEach((line, index) => {
    patterns.forEach(p => {
      const match = line.match(p.regex);
      if (match) {
        functions.push({
          name: match[1],
          line: index + 1,
          params: match[2] || 'none',
          purpose: `Handles ${match[1]} functionality`,
          type: p.type
        });
      }
    });
  });
  
  return functions.slice(0, 5); // Limit to 5 functions
};

// Helper: Get file content for KT
const getFileContentForKT = (fileName) => {
  // This would normally come from the actual file
  if (fileName === 'App.jsx') {
    return `import React from 'react';
import Button from './components/Button';
import Header from './components/Header';

function App() {
  const [count, setCount] = React.useState(0);
  
  const handleIncrement = () => {
    setCount(count + 1);
  };
  
  return (
    <div>
      <Header />
      <Button onClick={handleIncrement}>
        Count: {count}
      </Button>
    </div>
  );
}

export default App;`;
  }
  
  return `// Content for ${fileName}`;
};